# Generated by Django 5.1.4 on 2025-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_detail',
            field=models.CharField(max_length=400),
        ),
    ]
