# Generated by Django 5.2 on 2025-05-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_post_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_detail',
            new_name='subtitle',
        ),
    ]
